name: Validate Main PR Source

on:
  pull_request_target:
    branches: [main]

jobs:
  check-main-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR is from staging branch
        run: |
          # Check if the PR's source branch is 'stage'
          if [ "$GITHUB_BASE_REF" = "main" ] && [ "$GITHUB_HEAD_REF" != "stage" ]; then
            echo "Error: PRs to main must come from the staging branch."
            exit 1
          fi
